fix test cases
GrebNat/Python-TestAutomation-Training-Course pull request #1
Opened 2021-03-18 11:45 UTC by GrebNat

2021-03-20 17:10 UTC, zhidelev requested changes
После изменения на strip() можно замерджить 👍

2021-03-20 17:10 UTC, zhidelev commented on test_sample.py
> +    return test_string.replace(" ", "").replace("\t", "")
Привет. Вариант рабочий, в данном случае удобней было бы воспользоваться методом [strip()](https://docs.python.org/3/library/stdtypes.html?highlight=strip#str.strip) - он тоже покрывает тест-кейсы и выглядит лучше для чтения кода.
Поменяй, пожалуйста, на strip() и домашка сдана :+1:

2021-03-22 09:03 UTC, GrebNat commented on test_sample.py
> +    return test_string.replace(" ", "").replace("\t", "")
поправила

2021-03-23 19:01 UTC, zhidelev approved these changes
Отлично, сдано 👍 Можно мерждить!

2021-03-24 09:49 UTC, merged