hw2 с вопросами по 4 и 5 заданию
GrebNat/Python-TestAutomation-Training-Course pull request #2
Opened 2021-03-30 05:58 UTC by GrebNat

по 4 и 5 заданию есть вопросы - оставила в комментариях

2021-03-30 06:38 UTC, zhidelev commented
@GrebNat , привет,  пригласи ещё https://github.com/cptjohan, https://github.com/ZoiaOchikova, https://github.com/alpakhomov , если ещё не пригласила. После приёма приглашения я назначу ревью 👍

2021-03-30 08:02 UTC, GrebNat commented
> @GrebNat , привет, пригласи ещё https://github.com/cptjohan, https://github.com/ZoiaOchikova, https://github.com/alpakhomov , если ещё не пригласила. После приёма приглашения я назначу ревью 👍

@zhidelev, да, я их добавила в коллабораторы

2021-03-30 13:52 UTC, alpakhomov requested changes

2021-03-30 13:52 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw1.py
> +    return bool(re.match("[0-9]{4}(-[0-9]{2}){2}\n", date))
```suggestion
```
можно сразу возвращать, не кастить в bool Метод match вернет либо матч объект, либо None - и в соответствующем if этот None превратится в False, а любой не пустой объект в True https://docs.python.org/3/library/stdtypes.html#truth-value-testing

2021-03-30 13:52 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw1.py
> +    return file.name
```suggestion
```
Из функции нужно вернуть абсолютный путь https://docs.python.org/3/library/os.path.html#module-os.path

2021-03-30 13:52 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw2.py
> +        if not res.__contains__(el):
```suggestion
        if el not in res:
```
Метод __contains__ тут нет смысла вызывать, стоит пользоваться оператором in. Ну и в целом первый цикл не нужен - там ведь просто копия inp в res создается. Можно написать 
```
res, num = inp.copy(), []
```
Но и этого на самом деле делать не нужно, можно вместо res просто использовать изначальный inp

2021-03-30 13:52 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw2.py
> +        num.append(inp.count(res[i]))
```suggestion
    for i, el in enumerate(res):
        num.append(inp.count(el))
```
Пользуйся методом enumerate(some_collection); он вернет кортежи (индекс, элемент)

2021-03-30 13:52 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw3.py
> +    return res
Тесты проходят, но в целом задание было не в том чтобы реализовать алгоритм, а чтобы найти готовое решение в питоне. Тут все очень сложно (4 вложенных цикла), а можно сделать с помощью https://docs.python.org/3/library/itertools.html с одним циклом; тебе из этого модуля понадобится один из combinatoric iterators

2021-03-30 13:52 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw4.py
> +#прошу подсказку
Представь что у нас есть функция, которая вычисляет что-нибудь сложное и нам нужно много раз ее вызывать. Мы хотим запоминать результаты вызовов - если мы уже вызывали функцию с такими же параметрами, нам нужно будет просто вернуть значение которое запомнили, а не вычислять заново.
Этого можно добиться сделав функцию-обертку. В нее мы передаем нашу функцию-сложные-долгие-вычисления, обертка проверяет вызывалась ли уже функция с этими значениями. Если нет, то сохраняет в какой-то структуре или переменной значения аргументов, затем вызывает долгую функцию, и сохраняет результат, и возвращает его. Если уже вызывалась - то сразу возвращает результат (сравнивая видели ли мы уже такие аргументы)
Пользоваться такой оберткой можно будет так
```py
def func(a, b):
        return (a ** b) ** 2

cache_func = cache(func)
val_1 = cache_func(100, 200) # <- тут что-то вычисляется
val_2 = cache_func(100, 200) # <- тут не нужно вычислений, сразу вернем
```

2021-03-30 13:52 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw5.py
> +
В питоне все привыкли к функциям наподобие range или slice. Они могут принимать три параметра - start, stop, step. При этом принимают они их именно в таком порядке. Передать их по ключу range(stop=3, start=1, step=1) нельзя. Это сделано специально, потому что все привыкли к устоявшемуся порядку аргументов в такого рода функциях; если начать передавать их по ключу, то у читающего этот код взорвется мозг.
Кастом_рейнж который нужно реализовать здесь - это такая разновидность рейнжа. Он должен принимать первым аргументом коллекцию, а затем три опциональных - все те же start, stop, step; при этом не должно быть возможности передать ни один из этих аргументов по ключу, только позиционно, именно в таком порядке.
В этот custom_range можно передать только коллекцию (тогда он вернет ее всю), коллекцию и старт, колл+старт+стоп или все четыре параметра. В питоне это можно реализовать с помощью ```*args```

2021-04-03 20:48 UTC, GrebNat commented on Lecture_2_Collections_homework/hw1.py
> +    return bool(re.match("[0-9]{4}(-[0-9]{2}){2}\n", date))
fixed

2021-04-03 20:48 UTC, GrebNat commented on Lecture_2_Collections_homework/hw2.py
> +        if not res.__contains__(el):
done

2021-04-03 20:48 UTC, GrebNat commented on Lecture_2_Collections_homework/hw2.py
> +        num.append(inp.count(res[i]))
done

2021-04-03 20:48 UTC, GrebNat commented on Lecture_2_Collections_homework/hw3.py
> +    return res
done

2021-04-03 20:48 UTC, GrebNat commented on Lecture_2_Collections_homework/hw4.py
> +#прошу подсказку
done

2021-04-03 20:48 UTC, GrebNat commented on Lecture_2_Collections_homework/hw5.py
> +
done

2021-04-03 20:48 UTC, GrebNat commented on Lecture_2_Collections_homework/hw1.py
> +    return file.name
done

2021-04-03 20:48 UTC, GrebNat commented on Lecture_2_Collections_homework/hw1.py
> +    return file.name
done

2021-04-04 11:22 UTC, alpakhomov approved these changes
Все ок, можно мержить

2021-04-05 06:51 UTC, merged