hw4 with pytest and allure reports(source)
GrebNat/Python-TestAutomation-Training-Course pull request #4
Opened 2021-04-14 11:01 UTC by GrebNat

2021-04-14 14:29 UTC, alpakhomov requested changes
С позитивными тестами все отлично, по остальному
- сейчас если на вход передать дробь вида 1/0, то вернется пустой список. По идее должна быть ошибка деления на 0; ну и соответсвенно должен быть тест который проверяет что падает определенная ошибка
- не очень понял по test_cont_fraction_failed - он нужен просто чтобы показать в отчете красный тест? Наверное можно пометить его как падающий, для этого в pytest есть специальный маркер
- еще добавь плз папку tmp в gitignore, а то от нее куча мусора

2021-04-15 07:57 UTC, GrebNat commented
> * йчас если на вход передать дробь вида 1/0, то вернется пустой список. По идее должна быть ошибка деления на 0; ну и соответсвенно должен быть тест который проверяет что падает определенная ошибка

2021-04-15 08:04 UTC, GrebNat commented
> * сейчас если на вход передать дробь вида 1/0, то вернется пустой список. По идее должна быть ошибка деления на 0; ну и соответсвенно должен быть тест который проверяет что падает определенная ошибка

добавила проверку на 0 и негативный тест

> * не очень понял по test_cont_fraction_failed - он нужен просто чтобы показать в отчете красный тест? Наверное можно пометить его как падающий, для этого в pytest есть специальный маркер

да, добавила маркер

> * еще добавь плз папку tmp в gitignore, а то от нее куча мусора

удалила. но это не мусор, а данные для allure. репорт просили засабмитить в задании.

2021-04-15 08:09 UTC, alpakhomov approved these changes
Все отлично, можно мержить

2021-04-15 08:12 UTC, merged