hw6 done
GrebNat/Python-TestAutomation-Training-Course pull request #6
Opened 2021-04-23 04:08 UTC by GrebNat

У меня осталось недопонимание про порядок классов в файле, а именно - Student и HomeWorkResult.

они используются друг в друге (циклично, перекрестно... и как-то так). Как только я это написала, HomeworkResult класс не был виден из Student класс, так как шел после него... осле смены классов местами - обратная ситуация.

Собственно, вопросы:
 1. как обходить такие ситуации?
 2. что я сделала (могла сделать), чтобы в итоге финальный код заработал?

2021-04-29 06:42 UTC, alpakhomov requested changes
Если в твоем коде сейчас перенести класс HomeworkResult выше Student, то действительно будет ошибка NameError: name 'Student' is not defined
Она происходит из-за аннотаций типов - в этой строке
```py
def __init__(self, homework: Homework, solution: str, author: Student):
```
если убрать аннотацию у author, все будет работать.
Решить эту проблему не убирая тип автора можно с помощью импорта (он должен быть перед всеми остальными импортами
```py
from __future__ import annotations
```
Это превратит аннотации в стринги и решит проблему. Начиная с питона 3.10 (он еще не вышел), это будет дефолтным поведением и импорт будет не нужен. Больше здесь https://stackoverflow.com/a/33533514/2634302

2021-04-29 06:42 UTC, alpakhomov commented on Lecture_6_Testing_homework/impl.py
> +        self.created = homework.created
здесь наверное должно быть время создания HomeworkResult, а не самой домашки

2021-04-29 06:42 UTC, alpakhomov commented on Lecture_6_Testing_homework/impl.py
> +            self.homework_done.get(homework_result.homework).append(homework_result)
Это можно упростить. Вот пример использования defaultdict, он потому так и называется, что там не нужны проверки на существование ключа - если ключа нет, то defaultdict добавит его со значением по-умолчанию:
```
>>> a = defaultdict(list)
>>> a
defaultdict(<class 'list'>, {})
>>> a['foo'].append(1)
>>> a
defaultdict(<class 'list'>, {'foo': [1]})
```

2021-04-29 06:42 UTC, alpakhomov commented on Lecture_6_Testing_homework/oop_1.py
> +    temp_2 = Teacher.homework_done
Тут есть ошибка в проверке в самом задании, попробуй поменять строку 66 на
```py
temp_1 = opp_teacher.homework_done[oop_hw].copy()
```
и 69 на
```py
temp_2 = Teacher.homework_done[oop_hw]
```
После этих изменений твое решение будет падать на ассерте. В задании есть строчка "нужно гаранитровать остутствие повторяющихся результатов по каждому заданию", т.е. в словаре в списках с homework_result не должно быть дубликатов. В твоем решении нужно поменять list в defaultdict на другую структуру

2021-05-11 16:00 UTC, GrebNat commented on Lecture_6_Testing_homework/impl.py
> +        self.created = homework.created
done

2021-05-11 16:00 UTC, GrebNat commented on Lecture_6_Testing_homework/impl.py
> +            self.homework_done.get(homework_result.homework).append(homework_result)
done

2021-05-11 16:00 UTC, GrebNat commented on Lecture_6_Testing_homework/oop_1.py
> +    temp_2 = Teacher.homework_done
done

2021-05-11 16:28 UTC, alpakhomov approved these changes
Все отлично, можно мержить

2021-05-11 17:11 UTC, merged